# The development server is started with the command:
# docker compose -f compose.develop.yml up -d

services:
  nginx_nuki:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets/nginx:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - webapp_nuki


  webapp_nuki:
    build:
      dockerfile: Dockerfile
    container_name: webapp-nuki
    volumes:
      - ./secrets/webapp_nuki_mdb-postgres.env:/app/secrets/mdb-postgres.env:ro
      - ./secrets/webapp_nuki.dev.env:/app/secrets/.env.development:ro
    ports:
      - 8050:8050
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - APP_ENV=development
      - DASH_ASYNC_SUPPORT=0


# To (re)build images:       docker compose -f compose.develop.yml build
# To run/start images:       docker compose -f compose.develop.yml up
# To run/start images and leave running: docker compose -f compose.develop.yml up --detach     (or -d)
# To enter specific image:   docker compose exec -ti webapp_qeqert02 /bin/bash